name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # or 'master' depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js (for Firebase CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase service account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${HOME}/firebase-key.json"

      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --project todo-app-58739 --token "$(cat ${HOME}/firebase-key.json | jq -r .private_key_id)"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-key.json
