name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Save Firebase service account key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-key.json

      - name: Debug project ID
        run: echo "Project ID is '${{ secrets.PROJECT_ID }}'"

      - name: Debug credential file exists
        run: |
          echo "Credential file exists?"; ls -la $HOME/firebase-key.json
          echo "First few lines:"; head -n 5 $HOME/firebase-key.json

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: firebase deploy --only hosting --project ${{ secrets.PROJECT_ID }}


